export const FETCH_FAQ_SUCCESS = 'FETCH_FAQ_SUCCESS';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const CREATE_SERVICE_ERROR = 'CREATE_SERVICE_ERROR';
export const GET_FILTERED_TAGS_SUCCESS = 'GET_FILTERED_TAGS_SUCCESS';
export const GET_FILTERED_BOTH_SUCCESS = 'GET_FILTERED_BOTH_SUCCESS';
export const GET_FILTERED_CATEGORY_SUCCESS = 'GET_FILTERED_CATEGORY_SUCCESS';
export const TOGGLE_DISPLAY_CATEGORIES = 'TOGGLE_DISPLAY_CATEGORIES';
export const TOGGLE_TAG_MENU = 'TOGGLE_TAG_MENU';
export const TOGGLE_MENUOVERLAY = 'TOGGLE_MENUOVERLAY';
export const SET_SEARCHBOX_VIEW = 'SET_SEARCHBOX_VIEW';
export const TOGGLE_FILTERED_VIEW = 'TOGGLE_FILTERED_VIEW';
export const GET_SEARCHED_SERVICES_SUCCESS = 'GET_SEARCHED_SERVICES_SUCCESS';
export const TOGGLE_FAQ_MESSAGE = 'TOGGLE_FAQ_MESSAGE';
export const CREATE_FAQ_SUCCESS = 'CREATE_FAQ_SUCCESS';
export const CREATE_FAQ_ERROR = 'CREATE_FAQ_ERROR';
// index.js

export const FORM_HAS_SUBMITTED_SUCCESS = 'FORM_HAS_SUBMITTED_SUCCESS';
export const FORM_HAS_ERRORED = 'FORM_HAS_ERRORED';
export const FETCH_ERR_MSG_DATA = 'FETCH_ERR_MSG_DATA';
export const CURRENT_ROUTE = 'CURRENT_ROUTE';
